### ISSUE TITLE
Get device metrics on first installation

### ISSUE THREAD

**Issue by dobbz** [ekitabu-LLC/ekitabu-readium-desktop-working#53]
We need to grab some device metrics on first install and sync with MySQL. This will help us link the learning analytics data to device tracking data. For example using [systeminformation node module](https://www.npmjs.com/package/systeminformation)
Items to collect if available: 

1. Device -- Manufacturer, Model, Serial Number, UUID, sku -- `systeminformation.system().then(data => {console.log(data);})`
2. OS -- platform, distro, release, Type, codename, arch, kernel, serial, Build No, UUID -- `systeminformation.osInfo().then(data => {console.log(data);})`
3. CPU --  manufacturer, brand, speed, physicalcores, cores -- `systeminformation.system().then(data => {console.log(data);})`

_On linux serial and device UUID require elevation but on windows it works fine_

@mutterback : Should we discuss maybe adding `systeminformation.processes().then(data => {console.log(data);})` that will give us current running processes on the computer as per discussion with will

**Comment by brettins** [comment]
This task is already completed - we gather device information and sync it with the MySQL database. Are these items different than what's already implemented? Or is there a regression/bug?

**Comment by dobbz** [comment]
Sorry I wasn't clear. We need something that can uniquely identify a device and survive app reinstall like 
serial number/device uuid/OS uuid whichever can be gotten reliably. The Idea is when querying device tracking data we can point out the learning analytics data and vice versa.

Device Tracking is a system for tracking the physical location of the device and which school it is assigned. The data currently resides in Azure SQL server.

**Comment by mutterback** [comment]
Let me refine this to ask a specific question for Brett: Are we capturing
the Windows ID or Device Serial number in the code?

If so, Dobbz and Kevin are not seeing it in the data. If the case is it is
in code, but not in the data we're seeing, Brett, could you point to the
column in the MySQL table where this data is going?

We're trying to isolate what's going on here.
- is it in the code Yes/No
- if so, are we looking in the wrong place Yes/No
- if we're looking in the right place, is the data synching Yes/No

Thanks!
- Matt

**Comment by brettins** [comment]
So this is what we have in the code right now: 

https://github.com/ekitabu-LLC/ekitabu-readium-desktop-working/blob/7dddbb4a29d61b356c56baeebaaf3695f837ef28/src/main/di.ts#L273
```
        "_id" : "deviceInfo",
        "username":  os.userInfo().username,
        "cpus" : os.cpus(),
        "netinfo": os.networkInterfaces(),
        "platform" :os.platform(),
        "platformversion": os.release(),
        "ram": os.totalmem(),
        "architecture": os.arch(),
```

You can see what info this corresponds to here: 
https://nodejs.org/api/os.html

The network interface MAC addresses should uniquely identify devices, but we can also look at the Windows UUID. I seem to recall trying to capture it and it not being available on Electron, but it's been a while so I don't really remember now. 

There's a whole table called `device`, I believe, that should have all the info I've listed above here.

**Comment by brettins** [comment]
- is it in the code Yes/No
Some of it is, some of it isn't. Yes & No. 

- if so, are we looking in the wrong place Yes/No
I don't know where you're looking, sorry

- if we're looking in the right place, is the data synching Yes/No
That I'm not sure about.

**Comment by mutterback** [comment]
Thanks Brett,

I don't see what "_id" : "deviceInfo", is in the documentation

We need to add the Windows Serial Number and IMEI if available

If _id is not = to the Windows Serial Number, we need to add that to the
analytics.

**Comment by brettins** [comment]
`_id` is just pouchDB document identifier for the `deviceInfo` table. 

I'm getting back into this, and remembering why we don't have the Windows Serial Number. 

Getting the windows serial number is done with WMIC and requires admin privileges on the Windows account to run, so if we rely on this we would have to assume that users will start the application in admin mode, which I don't think is a good idea. 

IMEI might be feasible - is the Windows device you sent me similar to the ones that will have this software installed?  I can try capturing the IMEI on that and see what happens.

**Comment by brettins** [comment]
If the requirement, as Dobbz has requested, is a unique identifier that survives reinstalls, the network MAC address is our best bet.

**Comment by dobbz** [comment]
I've been testing the node module [systeminformation ](https://www.npmjs.com/package/systeminformation) and it grabs the system UUID and also device UUIID and serial number without requiring administrative access for windows and mac. Here's a sample of it's output.
`> si.system().then(data => console.log(data));
Promise { <pending> }
> {
  manufacturer: 'HP',
  model: 'HP Spectre x360 Convertible 13-ae0xx',
  version: '',
  serial: '5CD74222VR',
  uuid: '37444335-3234-3232-5652-523232344435',
  sku: '2VQ39PA#ABG'
}
> si.osInfo().then(data => console.log(data));
Promise { <pending> }
> {
  platform: 'win32',
  distro: 'Microsoft Windows 10 Pro Insider Preview',
  release: '10.0.20180',
  codename: '',
  kernel: '10.0.20180',
  arch: 'x64',
  hostname: 'dobbz',
  fqdn: 'DOBBZ.%USERDNSDOMAIN%',
  codepage: ' 437',
  logofile: 'windows',
  serial: '00331-20210-00000-AA737',
  build: '20180',
  servicepack: '0.0',
  uefi: false
}`

@brettins it may be worth checking to see if we can integrate this module. 
I also, confirmed that windows will not expose the mac address of a device that is not connected to a network.

@mutterback suggested we grab the distro, arch, os serial, and also the whole output of `si.system()` as shown above

**Comment by brettins** [comment]
Hey Dobbz, yep! Feels good for me to have been wrong on this one, though I'm not sure how I missed the system info when I researched this (and didn't test it when you posted it...jeez). 

```
{
[2]   platform: 'win32',
[2]   distro: 'Microsoft Windows 10 Pro',
[2]   release: '10.0.19041',
[2]   codename: '',
[2]   kernel: '10.0.19041',
[2]   arch: 'x64',
[2]   hostname: 'DESKTOP-SE7SQK0',
[2]   fqdn: 'DESKTOP-SE7SQK0.%USERDNSDOMAIN%',
[2]   codepage: ' 437',
[2]   logofile: 'windows',
[2]   serial: '00331-20300-00000-XXXXX',  #xxxx for privacy, it works properly in the output
[2]   build: '19041',
[2]   servicepack: '0.0',
[2]   uefi: false
[2] }
[2] {
[2]   manufacturer: 'MSI',
[2]   model: 'MS-7752',
[2]   version: '1.0',
[2]   serial: 'To be filled by O.E.M.',
[2]   uuid: 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF',
[2]   sku: 'To be filled by O.E.M.'
[2] }
[2] {
[2]   manufacturer: 'Intel®',
[2]   brand: 'Core™ i5-3570K',
[2]   vendor: 'GenuineIntel',
[2]   family: '6',
[2]   model: '58',
[2]   stepping: '9',
[2]   revision: '14857',
[2]   voltage: '',
[2]   speed: '3.40',
[2]   speedmin: '',
[2]   speedmax: '3.40',
[2]   governor: '',
[2]   cores: 4,
[2]   physicalCores: 4,
[2]   processors: 1,
[2]   socket: 'LGA1155',
[2]   cache: { l1d: 0, l1i: 0, l2: 1048576, l3: 6291456 }
[2] }
```

I'm not sure why I'm getting FFFFF-FFFF-FFFFFFF on my device ID, though. But this should enable us a whole bunch of new info. Great work @dobbz

**Comment by dobbz** [comment]
Probably the bios does not support storing a device UUID or more likely the manufacturer (MSI) never bothered to include it in the BIOS EEPROM. Probably that's why it's missing the serial and SKU.

**Comment by mutterback** [comment]
Assigned to @dobbz for review.

**Comment by dobbz** [comment]
@brettins I'm seeing an HTTP status code 500 in the logs for this build while it tries to access the prod api server. The dev api server  sends a status code of 401.

> [2] Error: Request failed with status code 500
> [2]     at createError (C:\Projects\eKitabu\Readium\Desktop\ekitabu-readium-desktop-working-brettfork\node_modules\axios\lib\core\createError.js:16:15)
> [2]     at settle (C:\Projects\eKitabu\Readium\Desktop\ekitabu-readium-desktop-working-brettfork\node_modules\axios\lib\core\settle.js:18:12)
> [2]     at IncomingMessage.handleStreamEnd (C:\Projects\eKitabu\Readium\Desktop\ekitabu-readium-desktop-working-brettfork\node_modules\axios\lib\adapters\http.js:202:11)
> [2]     at IncomingMessage.emit (events.js:228:7)
> [2]     at endReadableNT (_stream_readable.js:1185:12)
> [2]     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
> [2]   config: {
> [2]     adapter: [Function: httpAdapter],
> [2]     transformRequest: { '0': [Function: transformRequest] },
> [2]     transformResponse: { '0': [Function: transformResponse] },
> [2]     timeout: 0,
> [2]     xsrfCookieName: 'XSRF-TOKEN',
> [2]     xsrfHeaderName: 'X-XSRF-TOKEN',
> [2]     maxContentLength: -1,
> [2]     validateStatus: [Function: validateStatus],
> [2]     headers: {
> [2]       Accept: 'application/json, text/plain, */*',
> [2]       'Content-Type': 'application/json',
> [2]       'X-AUTH-TOKEN': '95ec549bc82ce343911fd0225a2ea84bb575f99bfbe2a6835f1b0b0f1d5664fca362b5b70b0e8bcae44d3eeeb95b11b989f409e730c864885912f5c7549864f7',
> [2]       'User-Agent': 'axios/0.18.1',
> [2]       'Content-Length': 2733
> [2]     },
> [2]     method: 'post',
> [2]     url: 'https://ereader-analytics-api.azurewebsites.net/device/info',
> [2]     data: '{"result":{"docs":[{"username":"dobbz","netInfo":{"vEthernet (WSL) 2":[{"address":"fe80::a9f8:1f98:d5f5:ab3d","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"00:15:5d:87:xx:xx","internal":false,"cidr":"fe80::a9f8:1f98:d5f5:ab3d/64","scopeid":57},{"address":"172.29.192.1","netmask":"255.255.240.0","family":"IPv4","mac":"00:15:5d:87:xx:xx","internal":false,"cidr":"172.29.192.1/20"}],"vEthernet (Wi-Fi)":[{"address":"fe80::ade1:bc39:cd0e:3b98","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"00:15:5d:d9:xx:xx","internal":false,"cidr":"fe80::ade1:bc39:cd0e:3b98/64","scopeid":68},{"address":"172.23.64.1","netmask":"255.255.240.0","family":"IPv4","mac":"00:15:5d:d9:xx:xx","internal":false,"cidr":"172.23.64.1/20"}],"Wi-Fi":[{"address":"fe80::64ab:c065:1ee7:c81a","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"90:61:ae:9e:xx:xx","internal":false,"cidr":"fe80::64ab:c065:1ee7:c81a/64","scopeid":21},{"address":"192.168.100.79","netmask":"255.255.255.0","family":"IPv4","mac":"90:61:ae:9e:xx:xx","internal":false,"cidr":"192.168.100.79/24"}],"Loopback Pseudo-Interface 1":[{"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","internal":true,"cidr":"::1/128","scopeid":0},{"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true,"cidr":"127.0.0.1/8"}],"vEthernet (Ethernet 2) 2":[{"address":"fe80::6d41:f467:5acd:7adc","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"00:15:5d:c7:xx:xx","internal":false,"cidr":"fe80::6d41:f467:5acd:7adc/64","scopeid":45},{"address":"172.17.48.1","netmask":"255.255.240.0","family":"IPv4","mac":"00:15:5d:c7:xx:xx","internal":false,"cidr":"172.17.48.1/20"}]},"ram":17014132736,"cpuInfo":{"manufacturer":"Intel┬«","brand":"CoreΓäó i7-8550U","vendor":"GenuineIntel","family":"6","model":"142","stepping":"10","revision":"","voltage":"","speed":"1.80","speedmin":"","speedmax":"1.99","governor":"","cores":8,"physicalCores":4,"processors":1,"socket":"BGA1356","cache":{"l1d":0,"l1i":0,"l2":1048576,"l3":8388608}},"sysInfo":{"manufacturer":"HP","model":"HP Spectre x360 Convertible 13-ae0xx","version":"","serial":"5CD74222VR","uuid":"37444335-3234-3232-5652-**********","sku":"2VQ39PA#***"},"osInfo":{"platform":"win32","distro":"Microsoft Windows 10 Pro Insider Preview","release":"10.0.20180","codename":"","kernel":"10.0.20180","arch":"x64","hostname":"dobbz","fqdn":"DOBBZ.%******%","codepage":" 437","logofile":"windows","serial":"00331-20210-00000-xxxxx","build":"20180","servicepack":"0.0","uefi":false},"_id":"deviceInfo","_rev":"1-679ea53b8fe058d6bee91837c8c1ff08"}],"warning":"No matching index found, create an index to optimize query time."}}'
> [2]   },

**Comment by brettins** [comment]
Hey @mocyeg what are the logs saying about the 500 errors?

**Comment by mocyeg** [comment]
@brettins @dobbz 

this was the migration thing again. please let me know if you continue to see 500's

**Comment by mocyeg** [comment]
@brettins @dobbz 

Ok I finally tracked this one down and [it's now fixed](https://github.com/ekitabu-LLC/ereader-analytics-api/commit/2ea9cd11270fa10045ee34381a000826944845e5)

Let me know if you run into another 500

**Comment by mutterback** [comment]
Hi @kevinmainairungu can 
- confirm that @brettins commit https://github.com/brettins/ekitabu-readium-desktop-working-brettfork/commit/638f02db07a47692fd28f83de58569680d27d912 is being pulled into your current build. We discussed Brett adding in the systeminfo in our call today (13 Jan 2021) However, it looks as if he already did this in that commit

- split off the HTTP status code 500 into a new issue for @dobbz to close

**Comment by mutterback** [comment]
@kevinmainairungu apologies, Mike already closed #69 so please just confirm that https://github.com/brettins/ekitabu-readium-desktop-working-brettfork/commit/638f02db07a47692fd28f83de58569680d27d912 closes this issue and is pulled into your build. Seems as if you should also think this issue to your PR to automatically close it when you merge.

**Comment by brettins** [comment]
Wow, I am a total space cadet, looks like I did do it. Just I didn't see the new database fields when I connected to the DB today, so we'll need to confirm that the new migrations are run before testing happens.

**Comment by mocyeg** [comment]
is that a new migration in `ereader-analytics-api` or something different?

**Comment by kevinmainairungu** [comment]
@mutterback Brett already merged this.

**Comment by mutterback** [comment]
HI Kevin, I think Mike is asking if the migration kicked in and actually
created the new fields in the database.

My take is that we need to be sure the change is reflected:
1. In the code so the data is grabbed
2. In the local database in the app
3. In the API so that the data is transmitted
4. In the MySQL database on Azure so the data has a home

However, the best way to test is to confirm that the data is getting into
the analytics db on Azure, then of course the other steps are working :-)
